# Generated by Django 4.2.4 on 2023-09-19 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_user_users_alter_comment_name_alter_post_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
