# Generated by Django 4.2.4 on 2023-09-28 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='Пост'),
        ),
    ]
